spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    mapper:
      default-view-inclusion: true

jwt:
  secret: "TtBGyKqHCqhRvC6ynQsCGzgZ8nVmgP5nCr95n5VdDDEYaJpSDpvAdzmaIFoLdlv6"
  refresh-expiration-ms: 604800000 # 7 days

server:
  port: 8443
  ssl:
      key-store: classpath:keystore.p12
      key-store-password: 123456
      key-store-type: PKCS12
      key-alias: springboot

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE